version: '3.7'

services:
  go-webserver:
    container_name: go-webserver-container
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/go/src/app
    ports:
      - 8080:8080
