apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webserver-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-webserver
  template:
    metadata:
      labels:
        app: go-webserver
    spec:
      containers:
        - name: go-webserver
          image: lvsena/go-webserver:latest
          ports:
            - containerPort: 8080
      