apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-webserver
  template:
    metadata:
      labels:
        app: go-webserver
    spec:
      containers:
        - name: go-webserver
          image: lvsena/go-webserver:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-webserver-service
spec:
  selector:
    app: go-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
      